# yamllint docker-compose.yml
---
name: inception

networks:
  inception-net:

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt

volumes:
  wordpress-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sganiev/data/wordpress-vol
  mariadb-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sganiev/data/mariadb-vol

services:

  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress-vol:/wordpress:ro
    networks:
      - inception-net
    init: true  # add init process for forwording signals and proper cleanup
    restart: on-failure
    depends_on:
      wordpress:
        condition: service_started  # replace with service_healthy ?
        restart: true
    env_file: .env

  wordpress:
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress-vol:/wordpress
    networks:
      - inception-net
    init: true
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
    secrets:
      - db_password
    env_file: .env
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password

  mariadb:
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb-vol:/var/lib/mysql
    networks:
      - inception-net
    init: true
    restart: on-failure
    secrets:  # maybe I need to specify them in build only
      - db_password
      - db_root_password
    env_file: .env
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    healthcheck:
      test: ["CMD-SHELL", "test -f /IS_HEALTHY.txt && mysqladmin ping --silent"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 40s
