server {
  listen 443;
  server_name localhost;
  client_max_body_size 500M;
  root /wordpress;
  index index.php index.html;

  location / {
    try_files $uri $uri/ =404;
  }

  location ~ \.php$ {
    # fastcgi_split_path_info ^(.+\.php)(/.+)$;

    # include fastcgi_params;
    # fastcgi_index index.php;

    # fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    # fastcgi_param PATH_INFO $fastcgi_path_info;
    include snippets/fastcgi-php.conf;
    fastcgi_pass wordpress:9000;
  }

  # ssl_protocols TLSv1.2 TLSv1.3;
}
